import EventualAndStrongEventualNotionsInPublicAnnouncements.BPALExtension
import EventualAndStrongEventualNotionsInPublicAnnouncements.Classification
import EventualAndStrongEventualNotionsInPublicAnnouncements.CommonBelief
import EventualAndStrongEventualNotionsInPublicAnnouncements.Compactness
import EventualAndStrongEventualNotionsInPublicAnnouncements.Definitions
import EventualAndStrongEventualNotionsInPublicAnnouncements.FalseOscillation
import EventualAndStrongEventualNotionsInPublicAnnouncements.FalsePreservation
import EventualAndStrongEventualNotionsInPublicAnnouncements.FalsePreservationCountermodels
import EventualAndStrongEventualNotionsInPublicAnnouncements.FalsePreservationModel
import EventualAndStrongEventualNotionsInPublicAnnouncements.FiniteConditions
import EventualAndStrongEventualNotionsInPublicAnnouncements.FirstOrder
import EventualAndStrongEventualNotionsInPublicAnnouncements.FixedPointForms
import EventualAndStrongEventualNotionsInPublicAnnouncements.Main
import EventualAndStrongEventualNotionsInPublicAnnouncements.NumericTraces
import EventualAndStrongEventualNotionsInPublicAnnouncements.OrdinalConditions
import EventualAndStrongEventualNotionsInPublicAnnouncements.OrdinalDynamics
import EventualAndStrongEventualNotionsInPublicAnnouncements.OrdinalReturn
import EventualAndStrongEventualNotionsInPublicAnnouncements.Oscillation
import EventualAndStrongEventualNotionsInPublicAnnouncements.PeelingModels
import EventualAndStrongEventualNotionsInPublicAnnouncements.Reduction
import EventualAndStrongEventualNotionsInPublicAnnouncements.Renaming
import EventualAndStrongEventualNotionsInPublicAnnouncements.ReversalSeparations
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichCommonBelief
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichDefinitions
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichExtension
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichFiniteConditions
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichFoundation
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichFixedPointForms
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichLanguage
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichLocality
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichMain
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichOrdinalConditions
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichOrdinalDynamics
import EventualAndStrongEventualNotionsInPublicAnnouncements.RichStrictness
import EventualAndStrongEventualNotionsInPublicAnnouncements.SingleAgent
import EventualAndStrongEventualNotionsInPublicAnnouncements.Strictness
import EventualAndStrongEventualNotionsInPublicAnnouncements.TruePreservation
import EventualAndStrongEventualNotionsInPublicAnnouncements.TruePreservationCountermodels

/-!
# Eventual and Strong Eventual Notions in Public Announcements

Complete entry point for the formalization of Eiji Yamada's manuscript.
See `EventualAndStrongEventualNotionsInPublicAnnouncements/COVERAGE.md` for
claim-by-claim declarations, model conventions, and source provenance.
-/
