import EventualAndStrongEventualNotionsInPublicAnnouncements.CommonBelief
import EventualAndStrongEventualNotionsInPublicAnnouncements.FiniteConditions

/-!
# Two-agent reversal separations

The witnesses of Lemma `lem:two-agent-reversal`. Lists are stored in reverse
order, so adding a child is `k :: xs`. The component generated by `[]` is the
paper's tree of finite strictly decreasing sequences. Allowing other lists as
additional worlds avoids dependent list types and does not affect that component.
-/

namespace EventualAndStrongEventualNotionsInPublicAnnouncements
namespace ReversalSeparations

open ClassificationSigmaValidity

universe u v w
variable {Agent : Type w} {Atom : Type v} {World : Type u}

/-- The alternating-agent possibility operator from Lemma 7. -/
def alternating (a b : Agent) (s : Atom) (χ : Formula Atom Agent) :
    Formula Atom Agent :=
  .or (.conj (.atom s) (.dia a (.conj (.neg (.atom s)) χ)))
    (.conj (.neg (.atom s)) (.dia b (.conj (.atom s) χ)))

def completion (a b : Agent) (ψ : Formula Atom Agent) : Formula Atom Agent :=
  .or ψ (.conj (.box a ψ) (.box b ψ))

def D (a b : Agent) : Formula Nat Agent := alternating a b 1 .verum

def theta10 (a b : Agent) : Formula Nat Agent :=
  .conj (D a b) (alternating a b 1 (.neg (D a b)))

def psi (a b : Agent) : Formula Nat Agent := .conj (.neg (.atom 0)) (D a b)

def theta01 (a b : Agent) : Formula Nat Agent := completion a b (psi a b)

theorem alternating_false_successor (M : Model World Atom Agent)
    (a b : Agent) (s : Atom) (χ : Formula Atom Agent) (x : World)
    (h : M.Satisfies x (alternating a b s (.neg χ))) :
    ∃ y, M.AnyStep x y ∧ ¬ M.Satisfies y χ := by
  simp only [alternating, Model.satisfies_or, Model.satisfies_and,
    Model.satisfies_dia, Model.satisfies_neg] at h
  rcases h with ⟨_, y, hxy, _, hy⟩ | ⟨_, y, hxy, _, hy⟩
  · exact ⟨y, ⟨a, hxy⟩, hy⟩
  · exact ⟨y, ⟨b, hxy⟩, hy⟩

theorem common_theta10_false (M : Model World Nat Agent) (a b : Agent)
    (x : World) (hC : Common M x (theta10 a b)) :
    ¬ M.Satisfies x (theta10 a b) := by
  intro hx
  obtain ⟨y, hxy, hy⟩ := alternating_false_successor M a b 1 (D a b) x hx.2
  exact hy (hC y (Relation.TransGen.single hxy)).1

theorem completion_at_target (M : Model World Atom Agent) (hM : IsK45 M)
    (a b : Agent) (ψ : Formula Atom Agent) {i : Agent} {x y : World}
    (hi : i = a ∨ i = b) (hxy : M.rel i x y) :
    M.Satisfies y (completion a b ψ) ↔ M.Satisfies y ψ := by
  have hyy : M.rel i y y := (hM i).2 hxy hxy
  simp only [completion, Model.satisfies_or, Model.satisfies_and,
    Model.satisfies_box]
  constructor
  · rintro (hy | ⟨ha, hb⟩)
    · exact hy
    · rcases hi with rfl | rfl
      · exact ha y hyy
      · exact hb y hyy
  · exact Or.inl

/-- A false completion has a false direct successor, by K45 target reflexivity. -/
theorem common_completion (M : Model World Atom Agent) (hM : IsK45 M)
    (a b : Agent) (ψ : Formula Atom Agent) (x : World)
    (hC : Common M x (completion a b ψ)) : M.Satisfies x (completion a b ψ) := by
  classical
  by_contra h
  have hboxes : ¬ (M.Satisfies x (.box a ψ) ∧ M.Satisfies x (.box b ψ)) :=
    fun hb => h ((M.satisfies_or x ψ (.conj (.box a ψ) (.box b ψ))).mpr (Or.inr hb))
  have hbad : (∃ y, M.rel a x y ∧ ¬ M.Satisfies y ψ) ∨
      (∃ y, M.rel b x y ∧ ¬ M.Satisfies y ψ) := by
    simpa only [Model.satisfies_box, not_and_or, not_forall, _root_.not_imp,
      exists_prop] using hboxes
  rcases hbad with ⟨y, hxy, hy⟩ | ⟨y, hxy, hy⟩
  · exact hy ((completion_at_target M hM a b ψ (Or.inl rfl) hxy).mp
      (hC y (Relation.TransGen.single ⟨a, hxy⟩)))
  · exact hy ((completion_at_target M hM a b ψ (Or.inr rfl) hxy).mp
      (hC y (Relation.TransGen.single ⟨b, hxy⟩)))

theorem theta10_finiteStageCondition (a b : Agent) :
    FiniteStageCondition.{u} true false (theta10 a b) := by
  apply (finiteStageCondition_reversal_iff true (theta10 a b)).mpr
  intro W M _ x hC
  exact common_theta10_false M a b x hC

theorem theta01_finiteStageCondition (a b : Agent) :
    FiniteStageCondition.{u} false true (theta01 a b) := by
  apply (finiteStageCondition_reversal_iff false (theta01 a b)).mpr
  intro W M hM x hC
  exact common_completion M hM a b (psi a b) x hC

namespace RankModel

abbrev State := List Nat

def shade : State → Bool
  | [] => true
  | _ :: xs => !(shade xs)

def below (k : Nat) : State → Prop
  | [] => True
  | m :: _ => k < m

def child (xs ys : State) : Prop := ∃ k, ys = k :: xs ∧ below k xs

def block (p x : State) : Prop := x = p ∨ child p x

def label (a b : Agent) (p : State) : Agent := if shade p then a else b

def relation (a b : Agent) (i : Agent) (x y : State) : Prop :=
  ∃ p, i = label a b p ∧ block p x ∧ child p y

def alive (n : Nat) : State → Prop
  | [] => True
  | k :: _ => n ≤ k

def positiveRank (n : Nat) : State → Prop
  | [] => True
  | k :: _ => n < k

def model (a b : Agent) (n : Nat) : Model State Nat Agent where
  rel i x y := relation a b i x y ∧ alive n y
  val p x := (p = 0 ∧ x = []) ∨ (p = 1 ∧ shade x = true)

theorem child_shade {p x : State} (h : child p x) : shade x = !(shade p) := by
  obtain ⟨k, rfl, _⟩ := h
  rfl

theorem child_parent_unique {p q x : State} (hp : child p x) (hq : child q x) :
    p = q := by
  obtain ⟨k, rfl, _⟩ := hp
  obtain ⟨l, h, _⟩ := hq
  exact (List.cons.inj h).2

theorem label_eq_shade (a b : Agent) (hab : a ≠ b) {p q : State}
    (h : label a b p = label a b q) : shade p = shade q := by
  unfold label at h
  cases hp : shade p <;> cases hq : shade q <;> simp_all

/-- Blocks for one fixed agent are disjoint. -/
theorem block_unique (a b : Agent) (hab : a ≠ b) {p q x : State}
    (hlab : label a b p = label a b q) (hp : block p x) (hq : block q x) : p = q := by
  have hs := label_eq_shade a b hab hlab
  rcases hp with rfl | hp
  · rcases hq with rfl | hq
    · rfl
    · have hc := child_shade hq
      cases h : shade q <;> simp_all
  · rcases hq with rfl | hq
    · have hc := child_shade hp
      cases h : shade p <;> simp_all
    · exact child_parent_unique hp hq

theorem model_isK45 (a b : Agent) (hab : a ≠ b) (n : Nat) :
    IsK45 (model a b n) := by
  intro i
  constructor
  · rintro x y z ⟨⟨p, hip, hpx, hpy⟩, _⟩ ⟨⟨q, hiq, hqy, hqz⟩, hz⟩
    have hpq := block_unique a b hab (hip.symm.trans hiq) (Or.inr hpy) hqy
    subst q
    exact ⟨⟨p, hip, hpx, hqz⟩, hz⟩
  · rintro x y z ⟨⟨p, hip, hpx, hpy⟩, _⟩ ⟨⟨q, hiq, hqx, hqz⟩, hz⟩
    have hpq := block_unique a b hab (hip.symm.trans hiq) hpx hqx
    subst q
    exact ⟨⟨p, hip, Or.inr hpy, hqz⟩, hz⟩

theorem relation_agent {a b i : Agent} {x y : State}
    (h : relation a b i x y) : i = a ∨ i = b := by
  obtain ⟨p, rfl, _, _⟩ := h
  unfold label
  cases shade p <;> simp

theorem relation_nonroot {a b i : Agent} {x y : State}
    (h : relation a b i x y) : y ≠ [] := by
  obtain ⟨p, _, _, k, rfl, _⟩ := h
  simp

/-- Opposite-shade edges are exactly the downward child edges. -/
theorem relation_opposite_iff (a b : Agent) (hab : a ≠ b) (x y : State) :
    (relation a b (label a b x) x y ∧ shade y = !(shade x)) ↔ child x y := by
  constructor
  · rintro ⟨⟨p, hi, hp, hy⟩, hshade⟩
    rcases hp with rfl | hp
    · exact hy
    · have hx := child_shade hp
      have hs := label_eq_shade a b hab hi
      cases h : shade p <;> simp_all
  · intro hy
    exact ⟨⟨x, rfl, Or.inl rfl, hy⟩, child_shade hy⟩

@[simp] theorem satisfies_r (a b : Agent) (n : Nat) (x : State) :
    (model a b n).Satisfies x (.atom 0) ↔ x = [] := by
  simp [Model.Satisfies, model]

@[simp] theorem satisfies_s (a b : Agent) (n : Nat) (x : State) :
    (model a b n).Satisfies x (.atom 1) ↔ shade x = true := by
  simp [Model.Satisfies, model]

theorem alternating_iff (a b : Agent) (hab : a ≠ b) (n : Nat)
    (x : State) (χ : Formula Nat Agent) :
    (model a b n).Satisfies x (alternating a b 1 χ) ↔
      ∃ k, below k x ∧ n ≤ k ∧ (model a b n).Satisfies (k :: x) χ := by
  have hL : (model a b n).Satisfies x (alternating a b 1 χ) ↔
      ∃ y, (model a b n).rel (label a b x) x y ∧
        shade y = !(shade x) ∧ (model a b n).Satisfies y χ := by
    simp only [alternating, Model.satisfies_or, Model.satisfies_and,
      Model.satisfies_dia, Model.satisfies_neg, satisfies_s]
    cases hs : shade x <;> simp [label, hs]
  rw [hL]
  constructor
  · rintro ⟨y, ⟨hxy, hyalive⟩, hshade, hχ⟩
    obtain ⟨k, rfl, hk⟩ := (relation_opposite_iff a b hab x y).mp ⟨hxy, hshade⟩
    exact ⟨k, hk, hyalive, hχ⟩
  · rintro ⟨k, hk, hn, hχ⟩
    have hchild : child x (k :: x) := ⟨k, rfl, hk⟩
    obtain ⟨hrel, hshade⟩ := (relation_opposite_iff a b hab x (k :: x)).mpr hchild
    exact ⟨k :: x, ⟨hrel, hn⟩, hshade, hχ⟩

theorem D_iff (a b : Agent) (hab : a ≠ b) (n : Nat) (x : State) :
    (model a b n).Satisfies x (D a b) ↔ positiveRank n x := by
  rw [D, alternating_iff a b hab]
  simp only [Model.satisfies_verum, and_true]
  cases x with
  | nil => exact ⟨fun _ => trivial, fun _ => ⟨n, trivial, le_rfl⟩⟩
  | cons k xs =>
    change (∃ m, m < k ∧ n ≤ m) ↔ n < k
    constructor
    · rintro ⟨m, hm, hn⟩
      omega
    · intro hn
      exact ⟨n, hn, le_rfl⟩

theorem theta10_iff (a b : Agent) (hab : a ≠ b) (n : Nat) (x : State) :
    (model a b n).Satisfies x (theta10 a b) ↔ positiveRank n x := by
  simp only [theta10, Model.satisfies_and, D_iff a b hab,
    alternating_iff a b hab, Model.satisfies_neg]
  constructor
  · exact And.left
  · intro hn
    refine ⟨hn, n, ?_, le_rfl, ?_⟩
    · cases x <;> exact hn
    · exact Nat.lt_irrefl n

theorem update_theta10 (a b : Agent) (hab : a ≠ b) (n : Nat) :
    (model a b n).update (theta10 a b) = model a b (n + 1) := by
  apply Model.ext'
  · intro i x y
    rw [Model.update_rel, theta10_iff a b hab]
    change ((relation a b i x y ∧ alive n y) ∧ positiveRank n y) ↔
      (relation a b i x y ∧ alive (n + 1) y)
    cases y with
    | nil => simp [alive, positiveRank]
    | cons k xs =>
      simp only [alive, positiveRank]
      constructor
      · rintro ⟨⟨hr, _⟩, hn⟩
        exact ⟨hr, by omega⟩
      · rintro ⟨hr, hn⟩
        exact ⟨⟨hr, by omega⟩, by omega⟩
  · intro p x
    rfl

theorem theta01_at_target (a b : Agent) (hab : a ≠ b) (n : Nat)
    {i : Agent} {x y : State} (hxy : (model a b n).rel i x y) :
    (model a b n).Satisfies y (theta01 a b) ↔ positiveRank n y := by
  rw [theta01, completion_at_target (model a b n) (model_isK45 a b hab n)
    a b (psi a b) (relation_agent hxy.1) hxy]
  simp only [psi, Model.satisfies_and, Model.satisfies_neg, satisfies_r,
    D_iff a b hab]
  exact ⟨And.right, fun hn => ⟨relation_nonroot hxy.1, hn⟩⟩

theorem update_theta01 (a b : Agent) (hab : a ≠ b) (n : Nat) :
    (model a b n).update (theta01 a b) = model a b (n + 1) := by
  apply Model.ext'
  · intro i x y
    rw [Model.update_rel]
    constructor
    · rintro ⟨hxy, hy⟩
      have hv := (theta01_at_target a b hab n hxy).mp hy
      change relation a b i x y ∧ alive (n + 1) y
      refine ⟨hxy.1, ?_⟩
      cases y with
      | nil => trivial
      | cons k xs => change n + 1 ≤ k; change n < k at hv; omega
    · intro hxy
      have hn : alive n y := by
        have hy := hxy.2
        cases y with
        | nil => trivial
        | cons k xs => change n ≤ k; change n + 1 ≤ k at hy; omega
      have hxy' : (model a b n).rel i x y := ⟨hxy.1, hn⟩
      refine ⟨hxy', (theta01_at_target a b hab n hxy').mpr ?_⟩
      have hy := hxy.2
      cases y with
      | nil => trivial
      | cons k xs => change n < k; change n + 1 ≤ k at hy; omega
  · intro p x
    rfl

theorem iterate_theta10 (a b : Agent) (hab : a ≠ b) (n : Nat) :
    (model a b 0).iterateUpdate (theta10 a b) n = model a b n := by
  induction n with
  | zero => rfl
  | succ n ih => rw [Model.iterateUpdate_succ, ih, update_theta10 a b hab]

theorem iterate_theta01 (a b : Agent) (hab : a ≠ b) (n : Nat) :
    (model a b 0).iterateUpdate (theta01 a b) n = model a b n := by
  induction n with
  | zero => rfl
  | succ n ih => rw [Model.iterateUpdate_succ, ih, update_theta01 a b hab]

theorem root_theta10 (a b : Agent) (hab : a ≠ b) (n : Nat) :
    (model a b 0).trace [] (theta10 a b) n := by
  rw [Model.trace, iterate_theta10 a b hab, theta10_iff a b hab]
  trivial

theorem root_theta01 (a b : Agent) (hab : a ≠ b) (n : Nat) :
    ¬ (model a b 0).trace [] (theta01 a b) n := by
  rw [Model.trace, iterate_theta01 a b hab]
  intro h
  have hpsi : ¬ (model a b n).Satisfies [] (psi a b) := by
    intro hp
    exact hp.1 ((satisfies_r a b n []).mpr rfl)
  have hboxes : (model a b n).Satisfies [] (.box a (psi a b)) ∧
      (model a b n).Satisfies [] (.box b (psi a b)) := by
    exact ((model a b n).satisfies_or [] (psi a b)
      (.conj (.box a (psi a b)) (.box b (psi a b)))).mp h |>.resolve_left hpsi
  have hedge : (model a b n).rel a [] [n] :=
    ⟨⟨[], rfl, Or.inl rfl, n, rfl, trivial⟩, le_rfl⟩
  have hDn : (model a b n).Satisfies [n] (D a b) := (hboxes.1 [n] hedge).2
  have hn : n < n := (D_iff a b hab n [n]).mp hDn
  exact Nat.lt_irrefl n hn

end RankModel

theorem theta10_not_eventual (a b : Agent) (hab : a ≠ b) :
    ¬ Eventual.{0} true false (theta10 a b) := by
  intro h
  obtain ⟨n, _, hn⟩ := h (RankModel.model a b 0)
    (RankModel.model_isK45 a b hab 0) [] (RankModel.root_theta10 a b hab 0)
  exact hn (RankModel.root_theta10 a b hab n)

theorem theta01_not_eventual (a b : Agent) (hab : a ≠ b) :
    ¬ Eventual.{0} false true (theta01 a b) := by
  intro h
  obtain ⟨n, _, hn⟩ := h (RankModel.model a b 0)
    (RankModel.model_isK45 a b hab 0) [] (RankModel.root_theta01 a b hab 0)
  exact RankModel.root_theta01 a b hab n hn

/-- Lemma 7: both reversal implications from finite S conditions are strict. -/
theorem reversal_separations (a b : Agent) (hab : a ≠ b) :
    (∃ φ : Formula Nat Agent, FiniteStageCondition.{0} true false φ ∧
      ¬ Eventual.{0} true false φ) ∧
    (∃ φ : Formula Nat Agent, FiniteStageCondition.{0} false true φ ∧
      ¬ Eventual.{0} false true φ) :=
  ⟨⟨theta10 a b, theta10_finiteStageCondition a b, theta10_not_eventual a b hab⟩,
    ⟨theta01 a b, theta01_finiteStageCondition a b, theta01_not_eventual a b hab⟩⟩

end ReversalSeparations
end EventualAndStrongEventualNotionsInPublicAnnouncements
