import EventualAndStrongEventualNotionsInPublicAnnouncements.RichLanguage

/-!
# Locality for common belief and nested announcements

The theorem is valid on arbitrary frames and for arbitrarily many agents.
Both current models must be forward closed on the comparison set. No compactness
or expressivity assumption is used.
-/

namespace EventualAndStrongEventualNotionsInPublicAnnouncements

open ClassificationSigmaValidity

universe u v w

variable {World : Type u} {Atom : Type v} {Agent : Type w}

/-- Positive paths remain within a forward-closed set and transfer along local
agreement of the accessibility relations. -/
theorem positivePath_mem_and_transfer {M N : Model World Atom Agent} {U : Set World}
    (hU : M.ForwardClosed U) (h : M.LocallyAgrees N U)
    {x y : World} (hx : x ∈ U) (hxy : Relation.TransGen M.AnyStep x y) :
    y ∈ U ∧ Relation.TransGen N.AnyStep x y := by
  induction hxy with
  | single hxy =>
      obtain ⟨a, ha⟩ := hxy
      have hy := hU hx a ha
      exact ⟨hy, Relation.TransGen.single ⟨a, (h.2 a x hx _ hy).mp ha⟩⟩
  | @tail y z hxy hyz ih =>
      obtain ⟨a, ha⟩ := hyz
      have hz := hU ih.1 a ha
      exact ⟨hz, ih.2.tail ⟨a, (h.2 a y ih.1 z hz).mp ha⟩⟩

namespace BPALC

/-- Locality with explicit current accessibility relations. This strengthened
form allows the announcement induction to change the current relations. -/
theorem satisfies_iff_of_locallyAgrees (M N : Model World Atom Agent)
    (φ : BPALCFormula Atom Agent) :
    ∀ (R S : Agent → World → World → Prop) (U : Set World),
      (BPAL.relationModel M R).ForwardClosed U →
      (BPAL.relationModel N S).ForwardClosed U →
      (BPAL.relationModel M R).LocallyAgrees (BPAL.relationModel N S) U →
      ∀ x, x ∈ U → (Satisfies M R x φ ↔ Satisfies N S x φ) := by
  induction φ with
  | atom p =>
      intro R S U hU hV h x hx
      exact h.1 p x hx
  | neg φ ih =>
      intro R S U hU hV h x hx
      exact not_congr (ih R S U hU hV h x hx)
  | conj φ ψ ihφ ihψ =>
      intro R S U hU hV h x hx
      exact and_congr (ihφ R S U hU hV h x hx) (ihψ R S U hU hV h x hx)
  | box a φ ih =>
      intro R S U hU hV h x hx
      constructor
      · intro hp y hy
        have hyU := hV hx a hy
        exact (ih R S U hU hV h y hyU).mp
          (hp y ((h.2 a x hx y hyU).mpr hy))
      · intro hp y hy
        have hyU := hU hx a hy
        exact (ih R S U hU hV h y hyU).mpr
          (hp y ((h.2 a x hx y hyU).mp hy))
  | common φ ih =>
      intro R S U hU hV h x hx
      constructor
      · intro hp y hy
        obtain ⟨hyU, hy'⟩ := positivePath_mem_and_transfer hV h.symm hx hy
        exact (ih R S U hU hV h y hyU).mp (hp y hy')
      · intro hp y hy
        obtain ⟨hyU, hy'⟩ := positivePath_mem_and_transfer hU h hx hy
        exact (ih R S U hU hV h y hyU).mpr (hp y hy')
  | announce φ ψ ihφ ihψ =>
      intro R S U hU hV h x hx
      let nextR : Agent → World → World → Prop :=
        fun a y z => R a y z ∧ Satisfies M R z φ
      let nextS : Agent → World → World → Prop :=
        fun a y z => S a y z ∧ Satisfies N S z φ
      have hU' : (BPAL.relationModel M nextR).ForwardClosed U := by
        intro y hy a z hyz
        exact hU hy a hyz.1
      have hV' : (BPAL.relationModel N nextS).ForwardClosed U := by
        intro y hy a z hyz
        exact hV hy a hyz.1
      have h' : (BPAL.relationModel M nextR).LocallyAgrees
          (BPAL.relationModel N nextS) U := by
        constructor
        · exact h.1
        · intro a y hy z hz
          exact and_congr (h.2 a y hy z hz) (ihφ R S U hU hV h z hz)
      exact ihψ nextR nextS U hU' hV' h' x hx

/-- Rich formulas have the same truth value in forward-closed, locally agreeing
models. This is the model-level API used by the general announcement dynamics. -/
theorem initiallySatisfies_iff_of_locallyAgrees {M N : Model World Atom Agent}
    {U : Set World} (hU : M.ForwardClosed U) (hV : N.ForwardClosed U)
    (h : M.LocallyAgrees N U) (x : World) (hx : x ∈ U)
    (φ : BPALCFormula Atom Agent) :
    InitiallySatisfies M x φ ↔ InitiallySatisfies N x φ := by
  apply satisfies_iff_of_locallyAgrees M N φ M.rel N.rel U
  · rw [BPAL.relationModel_rel_self]
    exact hU
  · rw [BPAL.relationModel_rel_self]
    exact hV
  · simpa only [BPAL.relationModel_rel_self] using h
  · exact hx

/-- Specialization to the set initially generated by a distinguished point. -/
theorem generated_initiallySatisfies_iff {M N : Model World Atom Agent}
    (x : World) (hN : N.ForwardClosed (M.generatedSet x))
    (h : M.LocallyAgrees N (M.generatedSet x)) (φ : BPALCFormula Atom Agent) :
    InitiallySatisfies M x φ ↔ InitiallySatisfies N x φ :=
  initiallySatisfies_iff_of_locallyAgrees (M.generatedSet_forwardClosed x) hN h x
    (M.reachable_refl x) φ

end BPALC

end EventualAndStrongEventualNotionsInPublicAnnouncements
